Add guava and use its Optional
```
E  FATAL EXCEPTION: main
E  Process: com.twobuffers.wire.sample_firebase_config, PID: 3728
E  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;
E      at com.twobuffers.wire.sample_firebase_config.di.DaggerAppComponent.firebaseRemoteConfigInitializer(DaggerAppComponent.java:74)
E      at com.twobuffers.wire.sample_firebase_config.di.DaggerAppComponent.setOfInitializer(DaggerAppComponent.java:82)
E      at com.twobuffers.wire.sample_firebase_config.di.DaggerAppComponent.initializers(DaggerAppComponent.java:86)
E      at com.twobuffers.wire.sample_firebase_config.di.DaggerAppComponent.injectSampleApp(DaggerAppComponent.java:110)
E      at com.twobuffers.wire.sample_firebase_config.di.DaggerAppComponent.inject(DaggerAppComponent.java:105)
E      at com.twobuffers.wire.sample_firebase_config.di.DaggerAppComponent.inject(DaggerAppComponent.java:34)
E      at dagger.android.DaggerApplication.injectIfNecessary(DaggerApplication.java:63)
E      at dagger.android.DaggerApplication.onCreate(DaggerApplication.java:38)
E      at com.twobuffers.wire.sample_firebase_config.SampleApp.onCreate(SampleApp.kt:13)
E      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
E      at android.app.ActivityThread.access$1500(ActivityThread.java:144)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
E      at android.os.Handler.dispatchMessage(Handler.java:102)
E      at android.os.Looper.loop(Looper.java:135)
E      at android.app.ActivityThread.main(ActivityThread.java:5221)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at java.lang.reflect.Method.invoke(Method.java:372)
E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E  Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Optional" on path: DexPathList[[zip file "/data/app/com.twobuffers.wire.sample_firebase_config-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E      ... 20 more
E      Suppressed: java.lang.ClassNotFoundException: java.util.Optional
E          at java.lang.Class.classForName(Native Method)
E          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E          ... 21 more
E      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```